### ISSUE TITLE
i have trained on multiple images The prediction output was correct when I tested on samples for trained images but If i gave a new face its predicting and matching from some of the trained ones with probability upto 99%. Please  help

### ISSUE THREAD

**Issue by kambojakhil1991** [rcmalli/keras-vggface#13]

**Comment by kambojakhil1991** [comment]
VGGFACE model is predition with 100% prob for non trained face image to some trained faces.
How to fx it if new face comes it should train model with that image

**Comment by ramonamorim** [comment]
i'm having the same problem, not exactly 100% but when i try a image from someone non trained face, the network result to the class with the best match, how can i say thats face is from somewone unknow?

**Comment by rcmalli** [comment]
Please share sample code or more explanation. For training, steps are same for every Keras model.
