### ISSUE TITLE
TypeError: _obtain_input_shape() got an unexpected keyword argument 'include_top'

### ISSUE THREAD

**Issue by HectorAnadon** [rcmalli/keras-vggface#14]
I am using keras 2.0.8. I got that error because apparently include_top is not used anymore. Instead require_flatten is used.

In order to fix it change line 84 to 

> require_flatten=include_top)

**Comment by rcmalli** [comment]
It is fixed with new release v0.4.

**Comment by wasifkhanniaz** [comment]
Hello,
I am compiling the below code for my problem:
 `model = VGG16(include_top=True, weights='imagenet')` but when run it, i got the following error: 
TypeError: _obtain_input_shape() got an unexpected keyword argument 'include_top'.

I am using Anaconda 3, Theano 2.0.9 and tensorflow 1.4.0.
How to solve this issue, any suggestions?

**Comment by taneta** [comment]
Still have this issue

**Comment by jeremyjordan** [comment]
i am also having this issue in keras 2.0.6

**Comment by muradalqurishee** [comment]
Hello Taneta,
in vgg16.py model line 102, edit include_top=include_top to require_flatten=include_top. The code is below
 input_shape = _obtain_input_shape(input_shape,
                                      default_size=224,
                                      min_size=48,
                                      data_format=K.image_data_format(),
                                      require_flatten=include_top)

**Comment by creative-h** [comment]
1. clone this git repo: "https://github.com/keras-team/keras-applications"
2. then import it " from keras import applications"
3. Now imoport vgg16  "from keras.applications.vgg16 import VGG16"

this will work for keras 2.2.4
