### ISSUE TITLE
What 2017 paper?

### ISSUE THREAD

**Issue by midaha** [rcmalli/keras-vggface#24]
'Based on RESNET50 architecture -> new paper(2017) '

I was wondering what paper this is referring to, as I cannot see a new VGGface paper from Oxford in their publication list.

Thanks.

**Comment by rcmalli** [comment]
It is  [cited](https://github.com/rcmalli/keras-vggface/blob/master/README.md#references) as second related paper in readme text. Writing names of the papers may be a good option for others.
