### ISSUE TITLE
Pre-processing of images

### ISSUE THREAD

**Issue by ghost** [rcmalli/keras-vggface#30]
Hey,
I'll be grateful if someone could answer if it is necessary to do the pre-processing of our particular images if we're trying to fine-tune this models.

In that case, I need to perform my own mean subtraction of that particular images?

Thank you.

**Comment by rcmalli** [comment]
For future users with the same problem, please check the [test code](https://github.com/rcmalli/keras-vggface/blob/ecaf687212fb269c6c59406cae2e9c099c23d5d7/test.py#L13).
