### ISSUE TITLE
Align faces before feature generation and comparison?

### ISSUE THREAD

**Issue by midaha** [rcmalli/keras-vggface#32]
All,
I'm experiencing very poor results when comparing images which have the face in different parts of the image (and perhaps different sizes), e.g. portrait photo vs a full-body photo.

I suspect that a face detection and alignment stage needs to be run. Does this need to match the specific alignment undertaken in the training stage?  Are there pixel coordinates for the eyes to be placed?  Presumably everyone is performing processing of this type before matching?

Any help is very much appreciated.

**Comment by rcmalli** [comment]
It will affect the final result. I suggest using the original paper's preprocessing steps.
