### ISSUE TITLE
keras_vggface on tensorflow-gpu

### ISSUE THREAD

**Issue by RadhikaaM** [rcmalli/keras-vggface#33]
Following are version:
tensorflow-gpu : 1.4
keras :2.1.6

Problem:
When installing keras_vggface with pip, it is uninstalling my tensorflow-gpu and installing tensorflow which is using CPU. I want it to use GPU.

Please tell me the solution for it.

Thanks

**Comment by luiscosio** [comment]
@RadhikaaM If you already have tensorflow-gpu installed, you should install it like this:

`pip install keras_vggface --no-dependencies`

**Comment by RadhikaaM** [comment]
Yes, It worked. Thanks a lot.

*Upasana Tiwari*
Student - MTech (Artificial Intelligence)
School Of Computer And Information Science
University Of Hyderabad
Contact Number - +91 - 9795533554

**Comment by ngxson** [comment]
This should be mention earlier. Running `pip install keras_vggface` broke the whole system !!
