### ISSUE TITLE
How to finetune last layers in keras vggface?

### ISSUE THREAD

**Issue by ZER-0-NE** [rcmalli/keras-vggface#36]
print(tf.__version__)
1.8.0
print(keras.__version__)
2.1.6
print(keras_vggface.__version__)
0.5

**Comment by rcmalli** [comment]
There are really good [blog posts](https://github.com/rcmalli/keras-vggface#projects--blog-posts) about this.

**Comment by jpgard** [comment]
Which of these blog posts shows how to fine-tune a pre-trained keras-vggface models? I don't see that in any of them.

**Comment by sherlockchou86** [comment]
you can set layer.trainable=False expect the last layers, and then re-train the last layers.
