### ISSUE TITLE
512 Features instead of 4096

### ISSUE THREAD

**Issue by ghost** [rcmalli/keras-vggface#37]
Hi there, thank you for posting this implementation. I have a question. I am confused at why I seem to be getting 512 dimensional representations when I set `include_top = False` instead of 4096 dimensions. I can get 4096 dimensional representations by setting `include_top = True` and using the output from layer `fc7`, however I am curious about what is going on in the former case. The 512 dimension representations seem to perform better for the purpose of comparing face similarity too.

**Comment by zhaochuanyun** [comment]
hi @ghost

In my opinion, when  include_top is set to False, it means we should write our own fine-tuning layers after the given model.

**Comment by rcmalli** [comment]
When you set the `include_top=False` the model does not have the fully connected layers. That is why you are only able to get 512 dimensions.
