### ISSUE TITLE
TF result seems not to be correct

### ISSUE THREAD

**Issue by thnkim** [rcmalli/keras-vggface#4]
The resulf of 'Prediction: Tensorflow backend with 'tf' dimension ordering' and 'Prediction: Theano backend with 'th' dimension ordering' are very different. 

Theano backend + th ordering is correct. 
Tensorflow backend + th ordering is correct.
But,
Tensorflow backend + tf ordering is wrong.

Thank you.

**Comment by knathanieltucker** [comment]
I am finding this to be wrong as well. @thnkim can you show me an example of how you got this making correct predictions?

**Comment by rcmalli** [comment]
I have released a new version of this project. Can you please reproduce it with new weights? The project uses Tensorflow backend as default and weights should be correct now. Please check readme file first for changes.

**Comment by knathanieltucker** [comment]
Works now. Thanks!
