### ISSUE TITLE
Which dataset are used to train your model?

### ISSUE THREAD

**Issue by Sithope** [rcmalli/keras-vggface#40]
1.4.0
2.1.1
0.5

I just want to ask which train dataset are trained to your rcmalli_vggface_tf_vgg16.h5
I downloaded LFW dataset but I find model is not apply to it.

**Comment by kevinisbest** [comment]
I think it was trained on [VGGFace2](http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/meta_infor.html), from the numbers of identities [here](https://github.com/rcmalli/keras-vggface/blob/60948a504bfd5dd74c98dce14889f0c5087c8500/keras_vggface/utils.py#L74).

**Comment by rcmalli** [comment]
Yes and the models are converted from original released source.

**Comment by sherlockchou86** [comment]
I found the number of identities is 9131 according to the VGGFace2 [paper](http://www.robots.ox.ac.uk/~vgg/publications/2018/Cao18/cao18.pdf)

> I think it was trained on [VGGFace2](http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/meta_infor.html), from the numbers of identities [here](https://github.com/rcmalli/keras-vggface/blob/60948a504bfd5dd74c98dce14889f0c5087c8500/keras_vggface/utils.py#L74).
