### ISSUE TITLE
I'm trying to test predictions on VGG Face test data and it is not producing the expected results

### ISSUE THREAD

**Issue by ksrinivs64** [rcmalli/keras-vggface#42]
I have a simple test based on the latest VGG test data:
model = VGGFace(model='resnet50')
img = image.load_img('test/n000001/0485_02.jpg', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = utils.preprocess_input(x, version=1)
preds = model.predict(x)
print(utils.decode_predictions(preds)[0][0][0])
It produces:
b' Stevie_Ray'
The picture of that of the Dalai Lama.
What datasets were used here?  Thanks!

**Comment by rcmalli** [comment]
Resnet50 and the Senet50 models should be used with `version=2`
