### ISSUE TITLE
Trainable param for predefined layers

### ISSUE THREAD

**Issue by iesahin** [rcmalli/keras-vggface#47]
```
TF: 1.13.0-dev20190204
Keras: 2.2.4
Keras-VGGFace 0.5
```

Keras has a `trainable` param for layers. I would like to set this to `False` when I load the predefined weights for fine tuning, so that only the top layers I define are trained. I probably can do this myself with a PR but is there another mechanism to achieve this?

**Comment by rcmalli** [comment]
This is mostly about customization. It can be added to the library if you would like to contribute.

**Comment by sherlockchou86** [comment]
no need to add to library, just set it if you want to fine-tuning by yourself.
