### ISSUE TITLE
The example on Feature extraction

### ISSUE THREAD

**Issue by piggyandy** [rcmalli/keras-vggface#7]
For feature extraction, wouldn't it simply be the code for "Prediction" except I would do:

`model = VGGFace(include_top=False, pooling='avg')` 

(this is with reference to Keras' [documentation](https://keras.io/applications/#extract-features-with-vgg16) on using their VGG16 model for feature extraction)

Moreover, I see that your code for pre-processing an image is similar to Keras' [pre_processing function for imagenet_utils](https://github.com/fchollet/keras/blob/master/keras/applications/imagenet_utils.py) except I noticed that the values for zero-center by mean pixel are different, are they supposed to be?

Thanks!!

**Comment by rcmalli** [comment]
For the first question, it really depends on the layer you want to extract features. The information you get will be a bit different between "pooling", "fc6" and "fc7".

For the second one, this network trained on the different dataset (Check the references) so, mean pixel values are also not same as ImageNet.

**Comment by piggyandy** [comment]
Thank you!
